### ISSUE TITLE
下载依赖的问题 、maven 配置https://clojars.org/repo/仓库也下载不了依赖

### ISSUE THREAD

**Issue by 1107186916** [schneiderlin/nrepl-starter#1]
![image](https://user-images.githubusercontent.com/65063196/197315406-06dc1be9-a6b3-4ffa-878e-a10f318122ad.png)
![image](https://user-images.githubusercontent.com/65063196/197315417-8bffe8d3-f60e-4778-9c77-d18bb2e3aeb2.png)

项目maven install 需要下载依赖。但是有些依赖是在https://clojars.org/repo/这个仓库中的，如果是把依赖下好后再放到本地仓库这样的做法麻烦并且路径也不好找。所以想着maven配置仓库的形式下载。但现在的问题是配置之后依赖仍然下载不了。有没有好的办法解决依赖问题吗，大佬。

**Comment by schneiderlin** [comment]
这个项目的 pom.xml 写了
```
  <repositories>
        <repository>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </releases>
            <url>https://repo.clojars.org</url>
            <id>clojars</id>
            <name>Codehaus Snapshots</name>
            <layout>default</layout>
        </repository>
    </repositories>
```
clojars 里面的包就会去 https://repo.clojars.org 下载, 应该是不需要额外设置 mirror 的.

麻烦上传完整的 maven 日志看看

**Comment by 1107186916** [comment]
![image](https://user-images.githubusercontent.com/65063196/197371162-10262326-e21d-49d9-ba92-d657b3ed8e65.png)
![image](https://user-images.githubusercontent.com/65063196/197371232-6952de72-eab9-40b9-b326-b8bc9e829f63.png)

是的。去掉了 mirror 也不行，如图。

**Comment by 1107186916** [comment]
build的日志：
[build-log.txt](https://github.com/schneiderlin/nrepl-starter/files/9845688/build-log.txt)


mvn install -e的日志:
[mvn install.txt](https://github.com/schneiderlin/nrepl-starter/files/9845709/mvn.install.txt)

**Comment by 1107186916** [comment]
或者可以的话，在github上提供一个jar和路径供我们这些下不了依赖的人使用。

**Comment by hjfree** [comment]
![image](https://user-images.githubusercontent.com/78492227/197394830-f39ac5e9-bc67-4120-9db7-b1ba667f4b46.png)
我的是改成默认的就能正常下载依赖了

**Comment by schneiderlin** [comment]
> build-log.txt

> Downloading from clojars: https://repo.clojars.org/luminus-http-kit/luminus-http-kit/0.1.9/luminus-http-kit-0.1.9.pom

> Failed to collect dependencies at luminus-http-kit:luminus-http-kit:jar:0.1.9: Failed to read artifact descriptor for luminus-http-kit:luminus-http-
kit:jar:0.1.9: Could not transfer artifact luminus-http-kit:luminus-http-kit:pom:0.1.9 from/to clojars (https://repo.clojars.org): Transfer failed 
for https://repo.clojars.org/luminus-http-kit/luminus-http-kit/0.1.9/luminus-http-kit-0.1.9.pom: Remote host closed connection during handshake: SSL peer shut down incorrectly -> 

下载地址是正确的, 但是传输失败了
看起来是网络问题, 不知道是不是和墙有关. 

#5 之后应该能解决

**Comment by schneiderlin** [comment]
> 或者可以的话，在github上提供一个jar和路径供我们这些下不了依赖的人使用。

已经上传到 maven central 了, 直接在项目中引入就可以
```
<dependency>
    <groupId>io.github.schneiderlin</groupId>
    <artifactId>nrepl-starter</artifactId>
    <version>1.0.8</version>
</dependency>
```

**Comment by schneiderlin** [comment]
closed, feel free to reopen if the problem persist
