### ISSUE TITLE
执行call method无反应

### ISSUE THREAD

**Issue by clickear** [schneiderlin/nrepl-starter#10]
操作步骤: 
1. 加载插件
2. 加下pom
3. 启动项目。控制台打印 repl.R.lambda$start$0(R.java:86) - Clojure nrepl is started on port(s): 7888 
4. start repl client
5. 调用方法错误。控制台无消息。

**Comment by schneiderlin** [comment]
pom 是什么版本
调用的方法签名是什么, 传的json是什么

**Comment by schneiderlin** [comment]
看起来似乎少了一步 "start repl client"

**Comment by clickear** [comment]
> pom 是什么版本 调用的方法签名是什么, 传的json是什么
有执行start repl client，但是似乎还是不行
pom版本: 1.0.9
idea插件版本: 0.02
idea版本 2022.2.3

json参数: 
<img width="364" alt="image" src="https://user-images.githubusercontent.com/12124172/201026615-5fe33fb3-b423-455b-b752-526733169155.png">

**Comment by clickear** [comment]
1. 很多方法调用都没有效果。
2. 部分方法调用，提示找不到类。
repl.R.callMethod(R.java:115) - Call method Exception
java.lang.NoSuchMethodException

**Comment by schneiderlin** [comment]
1.0.9 有点问题. 带了泛型参数的会提示 NoSuchMethodException. 先升级到1.1.0.
调用只包含基本类型参数的函数应该是可以的.

**Comment by clickear** [comment]
> 1.0.9 有点问题. 带了泛型参数的会提示 NoSuchMethodException. 先升级到1.1.0. 调用只包含基本类型参数的函数应该是可以的.

感谢回复。
1. 很多方法调用都没有效果。是由于gson版本冲突了。项目中使用的gson版本是2.8.2。改成2.9.1之后，可正常使用。
2. NoSuchMethodException已通过升级到1.1.0，解决了。
