### ISSUE TITLE
nested exception is java.lang.NoClassDefFoundError: clojure/lang/RT

### ISSUE THREAD

**Issue by hjfree** [schneiderlin/nrepl-starter#2]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'starterService' defined in class path resource [repl/config/StarterAutoConfigure.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [repl.R]: Factory method 'starterService' threw exception; nested exception is java.lang.NoClassDefFoundError: clojure/lang/RT

**Comment by hjfree** [comment]
![image](https://user-images.githubusercontent.com/78492227/197397207-417c6966-967d-4fd9-995c-b302cc621b16.png)

**Comment by schneiderlin** [comment]
clojure.lang.RT 应该会出现在 dependency 里面

刷新一下 maven, 看看能不能找到
<img width="181" alt="image" src="https://user-images.githubusercontent.com/17421608/197404475-63c2e727-fe77-4d6d-bc3e-94bdd50892a3.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/17421608/197404500-77612e03-8117-4827-8f21-aad8f76535a8.png">

或者把 maven 的 classpath 都打印出来, 看看有没有 clojure-1.10.0.jar

**Comment by hjfree** [comment]
已解决，之前是导入的jar包（<scope>system</scope><systemPath>${pom.basedir}/src/main/resources/nrepl-starter-1.0.7-SNAPSHOT.jar</systemPath>），导致其他依赖没引入，还是希望UP能传到中央仓库

**Comment by schneiderlin** [comment]
好的, 尽快传
