### ISSUE TITLE
idea 2022.2 安装后找不到

### ISSUE THREAD

**Issue by zcg** [schneiderlin/nrepl-starter#3]
![image](https://user-images.githubusercontent.com/68289686/197401437-73b1acd3-3b5a-40c4-914d-dbd753017ae2.png)

**Comment by schneiderlin** [comment]
啊我傻逼了, 测试的时候注释掉了, 打包没开回来. 我重新传一次

**Comment by schneiderlin** [comment]
> 啊我傻逼了, 测试的时候注释掉了, 打包没开回来. 我重新传一次

good catch
https://github.com/schneiderlin/nrepl-starter/releases/tag/1.0.7-2022-10-23 重新上传了
